version: '4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockerweb_4
    ports:
    - "8080:80"
    volumes:
    - ./:/webapp4
  redis:
    image: "redis:alpine"